name: Deploy frontend
on:
  push:
    branches:
      - "develop"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Do Something with env files
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo $ENV_FILE | base64 --decode > .env
      - name: Build page
        run: npm run build
      - name: Push to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          remote: /var/www/remotedev.team/html/
          host: ${{secrets.DEV_HOST}}
          username: ${{secrets.DEV_HOST_USER}}
          password: ${{secrets.DEV_HOST_PASSWORD}}
          port: ${{secrets.DEV_HOST_PORT}}
      - run: echo "🍏 This job's status is ${{ job.status }}."
