name: Deploy app
on:
  push:
    branches: [develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: push to server and build
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.DEV_HOST }}
          PORT: ${{ secrets.DEV_HOST_PORT }}
          USERNAME: ${{ secrets.DEV_HOST_USER }}
          PASSWORD: ${{ secrets.DEV_HOST_PASSWORD }}
          script: cd ${{ secrets.DEV_HOST_HOME }} && git pull origin develop && npm start
